pull_request_rules:
  - name: Test passed
    conditions:
      - base=master
      - "status-success=Code lint check"
      - "status-success=Run Python Tests"
      - "status-success=docs/readthedocs.org:pymilvus-orm"
    actions:
      label:
        add:
          - ci-passed

