pull_request_rules:
  - name: Test passed
    conditions:
      - base=main
      - "status-success=Code lint check (3.6)"
      - "status-success=Run Python Tests (3.6)"
    actions:
      label:
        add:
          - ci-passed

